# Generated by Django 6.0.1 on 2026-01-31 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('countInStock', models.IntegerField()),
                ('image', models.ImageField(upload_to='product_images/')),
                ('createdAt', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
